# Generated by Django 5.0.1 on 2024-04-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_author_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogspot',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('post', models.TextField()),
                ('thumbnail', models.ImageField(default='', upload_to='iamges/')),
            ],
        ),
    ]
