# Generated by Django 5.0.4 on 2024-05-06 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_blogspot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Blogspot',
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
