# Generated by Django 5.0.4 on 2024-05-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_remove_book_author_delete_blogspot_delete_signup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_question_1', models.CharField(max_length=100)),
                ('security_answer_1', models.CharField(max_length=100)),
                ('security_question_2', models.CharField(max_length=100)),
                ('security_answer_2', models.CharField(max_length=100)),
                ('security_question_3', models.CharField(max_length=100)),
                ('security_answer_3', models.CharField(max_length=100)),
            ],
        ),
    ]
